# Generated by Django 5.1 on 2024-08-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('img', models.FileField(upload_to='media')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('age', models.IntegerField()),
                ('loc', models.CharField(max_length=100)),
                ('exp', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('edu1', models.TimeField()),
                ('edu2', models.TextField()),
                ('Specialisation', models.TextField()),
                ('Approaches', models.TextField()),
                ('Fees', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('contat', models.CharField(max_length=100)),
                ('know1', models.TextField()),
                ('know2', models.TextField()),
                ('know3', models.TextField()),
                ('know4', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='therapizdetails',
            name='img',
            field=models.FileField(upload_to='media'),
        ),
    ]
