# Generated by Django 5.1 on 2024-08-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_profiles_edu1_alter_profiles_edu2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapizdetails',
            name='tid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapizdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
