# Generated by Django 5.1 on 2024-08-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_therapizdetails_tid_alter_therapizdetails_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='therapizdetails',
            name='tid',
        ),
        migrations.AlterField(
            model_name='therapizdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
