# Generated by Django 5.1 on 2024-08-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_register_remove_therapizdetails_tid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('therapist', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
