# Generated by Django 5.1 on 2024-08-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapizdetails',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
